### ISSUE TITLE
The obproxy default port should be 2881

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#11]
In these document
https://github.com/oceanbase/obdeploy/blob/master/example/distributed-with-obproxy-example.yaml
https://github.com/oceanbase/obdeploy/blob/master/example/mini-distributed-with-obproxy-example.yaml
https://github.com/oceanbase/obdeploy/blob/master/example/mini-single-with-obproxy-example.yaml
https://github.com/oceanbase/obdeploy/blob/master/example/mini-single-with-obproxy-example.yaml
https://github.com/oceanbase/obdeploy/blob/master/example/single-with-obproxy-example.yaml

The obproxy's port is 2883, but it should be same as observer's default port,  it should be 2881

**Comment by frf12** [comment]
fixed by #7
