### ISSUE TITLE
[浦发银行] micro_block_merge_verify_level block upgrade from 3.1.2 to 3.1.3-ce-bp

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#116]
For details, please refer to https://open.oceanbase.com/ask/detail?id=33800008

【问题描述】obd从1.2.1升级到1.3.3，然后用obd将原3.1.2版本ob集群升级到3.1.3-ce-bp版本，OBD升级oceanbase-ce 3.1.3报错，upgrade is not allowed temporarily。

执行升级命令是:obd cluster upgrade obtest -c oceanbase-ce -V 3.1.3 -v

[work around]
已解决。

micro_block_merge_verify_level 用于设置合并时宏块的校验级别。

在做benchmarkSQL 5.0测试集群性能时，为了性能最优将改参数修改为0。教程见https://open.oceanbase.com/docs/observer-cn/V3.1.3/10000000000096614

但是OBD升级集群时，会校验这个值必须是2或者3才可以。

**Comment by frf12** [comment]
这个项目是个集群级的配置项。我们的升级是滚动升级，不停服的。如果升级的时候主动先改到2或以上，升级后在调回来的话会导致用户在不感知不停服的情况被修改了一个与性能有关的配置项，可能会导致服务整体响应和吞吐下跌。

我们不应该去自动修改这种重要的配置项。还是此处OBD会选择报错并通知用户修改，用户应该在合适的时机修改此项目后在继续升级。
