### ISSUE TITLE
[Bug]: obd failed connect to observer if the password of root@sys is not modified by obd itself.

### ISSUE THREAD

**Issue by zetatez** [oceanbase/obdeploy#117]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version: observer V3.1.3
```

### Fast Reproduce Steps(Required)

1. deploying a OB cluster by obd and without setting the password of root
2. login into the root@sys, change the password of root user
3. issuing `obd cluster display cluster-name`, then failure occurs

### Actual Behavior

obd will failed connect to observer if the password of root@sys is not modified by obd itself.

### Expected Behavior

obd should still be able to connect to observer(such as, by providing obd a corect password of root@sys), even the password of root@sys is not modified by obd itself.  

Should not let user to fix it by following steps
1. login into root@sys, 
2. alter root password to '', 
3. modify the pasword by obd cluster edit-config ...
4. ...

### other information

nop

**Comment by frf12** [comment]
When the observer receives the request to change the password of root@sys, it will not notify OBD, nor should do so. Observer will not provide an interface to get the root@sys password because it is not secure. Therefore, we recommend tha use OBD to modify the root@sys password instead of logging in to the database to execute SQL.

**Comment by zetatez** [comment]
But this behavior will bring confusion to users. Your are right, observer should not notify obd the password is changed, but if the user know the password is changed, at least they should can use obd to access observer by providing the password of root@sys.

**Comment by zetatez** [comment]
BTW, it's seems that obd will reset parameters of observer if we use obd to restart the obcluster. Is also does not seem reasonable. Such as, I deployed a OB standalone cluster, then I can not modify the rootservice_list through login into root@sys, nor i can change the ip through `obd cluster edit-config ...`. It's a dead end.

**Comment by zetatez** [comment]
A better solution is that after the initial deployment, as long as the OBD knows the password, it should synchronize parameters from the OB cluster every time it calls the OBD, rather than vice versa
