### ISSUE TITLE
Failed to run tpch test after modify root@sys password by SQL

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#121]
It will report 
```
obd test tpch 3node  --tenant=test -s 100 --remote-tbl-dir=/data/ob/tpch100
Get local repositories and plugins ok
Open ssh connection ok
Cluster status check ok
Connect observer(server1(172.30.62.xxx):2881) x
[ERROR] Failed to connect to the server
See https://open.oceanbase.com/docs/obd-cn/V1.3.0/10000000000099584.
```

Due to obd failed to connect ob server with root@sys, once the password of root@sys has been modified by SQL 

Suggest:
1. provide more log error message. 
2. provate one error code.

**Comment by gys-git** [comment]
When running tests with OBD, it uses its own managed cluster and connection information. If you directly modify the OceanBase password using SQL, OBD will be unable to detect it and will lead to inability of maintenance management. To modify the OceanBase password, you need to use the obd edit-config command to make changes.
