### ISSUE TITLE
Question about [ERROR] No such install plugin for obproxy-3.2.0

### ISSUE THREAD

**Issue by bo-er** [oceanbase/obdeploy#125]
I'm installing Oceanbase on centOS 7

```
Linux ob1 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
I get this error and the error message is kind of confusing:
```
[root@ob1 ~]# obd cluster autodeploy ob-test -c ob-deploy.yml  -A
oceanbase-ce-3.1.4 already installed.
Package obproxy-3.2.0 is available.
obagent-1.1.2 already installed.
[ERROR] No such install plugin for obproxy-3.2.0
```
What does this message mean? `Install` is a verb, not a noun. I think this should be replaced with `[ERROR] No such plugin for installing obproxy-3.2.0`. Correct me if I'm wrong.

**Comment by gys-git** [comment]
You can redeploy using the latest version of OBD. If you encounter any issues during the process, please create a new issue and provide information about your deployment environment and error logs.
