### ISSUE TITLE
[Question] Cluster bootstrap x [ERROR] Cluster init failed

### ISSUE THREAD

**Issue by bo-er** [oceanbase/obdeploy#126]
Our team members are deploying oceanBase on 3-node clusters, we all end up with this error message:

```
Initialize cluster
Cluster bootstrap x
[ERROR] Cluster init failed
See https://open.oceanbase.com/docs/obd-cn/V1.4.0/10000000000436999 .
```
This is not recorded on the document.

**Comment by gys-git** [comment]
You can redeploy using the latest version of OBD. If you encounter any issues during the process, please create a new issue and provide information about your deployment environment and error logs.
