### ISSUE TITLE
[feat.]: Failed to display the OBServer's port

### ISSUE THREAD

**Issue by hindleyzeng** [oceanbase/obdeploy#133]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
安装的时候，显示observer端口异常，实际端口正常，属于显示问题
```

### other information

![image](https://user-images.githubusercontent.com/20276618/192416160-0cc3cdef-2f86-4779-ba3d-7beff7d02a84.png)

**Comment by longdafeng** [comment]
Could you please provide more details, otherwise it is hard to do further action. 

1. hardware information
2. obd log
3. os information
4. ssh information
5. the procedure of the bug

**Comment by frf12** [comment]
When the initialization is just completed, only the root service information in the cluster is complete, and other servers in the zone need to wait for a while, so the display at this time may lack some information. You can confirm by `obd cluster display<deploy name>`

**Comment by gys-git** [comment]
Due to the lack of response over an extended period, we will close this issue for now. If there are further requirements in the future, please feel free to open a new issue.
