### ISSUE TITLE
[Question]: [ERROR] BenchmarkSQL jar file not found at /usr/ob-benchmarksql/OB-BenchmarkSQL-5.0.jar. Please use `--bmsql-jar` to set BenchmarkSQL jar file

### ISSUE THREAD

**Issue by FrankXMX** [oceanbase/obdeploy#139]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

[root@77aa13b9ca07 ~]# obd test tpcc obcluster
Get local repositories and plugins ok
Open ssh connection ok
Cluster status check ok
Connect to observer ok
**[ERROR] BenchmarkSQL jar file not found at /usr/ob-benchmarksql/OB-BenchmarkSQL-5.0.jar. Please use `--bmsql-jar` to set BenchmarkSQL jar file**
See https://www.oceanbase.com/product/ob-deployer/error-codes .

**Comment by hnwyllmm** [comment]
yum install obtpcc

**Comment by longdafeng** [comment]
obtpcc hasn't been officially supported, right now, it just for testing.

**Comment by hnwyllmm** [comment]
yum install obtpcc

发自我的iPhone

**Comment by FrankXMX** [comment]
`yum install obtpcc`
Is it available in openEuler?

**Comment by gys-git** [comment]
You can find and download the appropriate tpcc RPM package for your operating system from the following link: https://mirrors.oceanbase.com/development-kit/el/ and install the tpcc environment.

**Comment by sunmin89** [comment]
If your archtecture is neither x86_64 nor aarch64, the prebuilt tpcc packages should not be available for you(https://mirrors.oceanbase.com/development-kit/el/9/)

You should read this guide.:
https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001033259

1.prepare ant build tool and jdk_1.8

2.Download benchmarksql 5.0 (https://sourceforge.net/projects/benchmarksql/files/latest/download/)

![image](https://github.com/user-attachments/assets/0130d942-830f-44a1-bcdb-2acba4306321)

3.Modify benchmarksql 5.0 source code and shell script to add  support for oceanbase

![image](https://github.com/user-attachments/assets/dc9e8f04-8caf-4756-8bb4-4159019123ba)

4. build benchmarksql 5.0 with ant

![image](https://github.com/user-attachments/assets/744d1f9c-587b-4677-8cf9-be80c7414a13)

5.  call obd.sh with `--bmsql-dir`
```
./tools/deploy/obd.sh tpcc -n DEPLOY_NAME --bmsql-dir /mnt/shared/sunmin/benchmarksql-5.0/
or
obd test tpcc obcluster --bmsql-dir /mnt/shared/sunmin/benchmarksql-5.0/
```
