### ISSUE TITLE
[Bug]: command 'obd cluster destroy' will delete all files

### ISSUE THREAD

**Issue by wyfanxiao** [oceanbase/obdeploy#145]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Fast Reproduce Steps

from :  https://ask.oceanbase.com/t/topic/35600583

### Actual Behavior

rm -fr %s/' % (path)

### Expected Behavior

rm -fr 'only oceanbase files'

**Comment by longdafeng** [comment]
This action is by design. 

If you want to reserve the cluster, you can directly use 'obd cluster stop' command
