### ISSUE TITLE
[Enhancement.]:  Please provide one hint to tell user that the yaml configuration is illegal

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#149]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
It is very easy to make the yaml illegal, for examle the space is in the wrong place. 

when install a cluster, please check the yaml firstly, if it  is illegal, please directly tell the user that the yaml configuration is illegal.
```

**Comment by gys-git** [comment]
The latest version of OBD now supports this feature.
