### ISSUE TITLE
[Bug]: dead document link

### ISSUE THREAD

**Issue by linsinan1995** [oceanbase/obdeploy#157]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
not relevant.
```

### Fast Reproduce Steps

The link https://www.oceanbase.com/product/ob-deployer/error-codes is dead and can not be accessed.  likely from https://github.com/oceanbase/obdeploy/blob/5a5bf043dcb864d6cd706a1804c8d20785157cc9/_errno.py#L53

```
[ 50s ] thds: 16 tps: 151136.95 qps: 151136.95 (r/w/o: 151136.95/0.00/0.00) lat (ms,95%): 0.21 err/s: 0.00 reconn/s: 0.00
Recover ok
[ERROR] Failed to recover system_config

See https://www.oceanbase.com/product/ob-deployer/error-codes .
```
Plz make an update.

### Actual Behavior

not relevant.

**Comment by frf12** [comment]
Thank you for your feedback. It is working now
