### ISSUE TITLE
[Bug]: OBD test holding the obd lock is too long

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#159]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
When run obd tests, it will failed to run other obd command such as "obd cluster display"


[ERROR] Another app is currently holding the obd lock.
```
```


### Fast Reproduce Steps

```
obd test tpch default -s 10 --remote-tbl-dir=/tmp/tpch -database=tpch --disable-transfer
```

start another terminate
```
obd cluster display default
[ERROR] Another app is currently holding the obd lock.
```

### Actual Behavior

reduce the time of holding the obd lock

### Expected Behavior

_No response_

### Other Information

_No response_

**Comment by frf12** [comment]
The display command is no longer held a lock now
