### ISSUE TITLE
[Bug]: obd工具指定–server参数异常

### ISSUE THREAD

**Issue by lijiaman1** [oceanbase/obdeploy#171]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
【 使用环境 】测试环境
【 OB or 其他组件 】obd
【 使用版本 】OceanBase Deploy: 2.0.1
```

### Fast Reproduce Steps

【问题描述】我的数据库存在3个节点，我重启2个服务器进行高可用测试，IP分别是
```shell
192.168.10.11     --> 服务器重启，observer进程没有拉起
192.168.10.12     --> 服务器关闭
192.168.10.13     --> 服务器开启，observer进程运行正常
```
测试完成后，我想使用obd先把192.168.10.11服务器的数据库拉起，发现如下报错：
```shell
root@observer1 oceanbase]# obd cluster start ob41test --servers="192.168.10.11"
Get local repositories ok
Search plugins ok
Open ssh connection x
[ERROR] OBD-1013: root@192.168.10.12 connect failed: time out

Trace ID: 8d23d7c0-fec3-11ed-ae74-000c299009ef
If you want to view detailed obd logs, please run: obd display-trace 8d23d7c0-fec3-11ed-ae74-000c299009ef
```

### Actual Behavior

从报错里面可以看到，如果`192.168.10.12`服务器没启动，则无法使用obd来启动`192.168.10.11`节点数据库。后续我把192.168.10.12服务器拉起来，obd运行才正常。

**我的问题**：2个节点是没有关系的，不能因为192.168.10.12服务器连不上就无法使用obd管理其他节点吧？

**Comment by hnwyllmm** [comment]
from : https://ask.oceanbase.com/t/topic/35603576/4
