### ISSUE TITLE
[Feat.]: 部署集群时是否可以指定不生成随机密码？

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/obdeploy#172]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
我希望obd 有类似MySQL初始化时的 --insecure 功能，不设置密码。这样可以方便搭建测试环境。
```

**Comment by gys-git** [comment]
如果有这需求可以在配置文件中指定密码为空即可，但是考虑到安全 需要慎用
