### ISSUE TITLE
[Bug]: The setting of system memory is not reasonable in the default example configuration

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#183]
### Describe the bug

![image](https://github.com/oceanbase/obdeploy/assets/374091/baad1a6e-dbb0-4966-8881-a76c5ee9a431)

### Environment

The memory_limit is 64g, but the system_memory is 30g, it doesn't make sense. 

### Fast reproduce steps

suggest adjust the system_memory as 10g

**Comment by gys-git** [comment]
This issue will be fixed in obd 2.9.0.
