### ISSUE TITLE
[Enhancement]: 更快捷的方式创建指定版本的oceanbase demo

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/obdeploy#196]
### Description

希望能够支持使用最直观的方式指定obd demo 部署的版本号，比如 `obd demo -c oceanbase-ce --oceanbase-ce.version=V4.2.1_CE_BP3`。

---

当前使用obd demo 创建指定版本的集群时，必须使用 4.2.1.5 这种方式书写版本号，但是这个版本号不容易获取。
我的场景：
我在[文档](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000589493)中看到V4.2.1_CE_BP3支持了某个功能，想要测试一下这个版本，我期望下面的命令就可以部署起来一个 V4.2.1_CE_BP3 版本的集群：

```
obd demo -c oceanbase-ce --oceanbase-ce.version=V4.2.1_CE_BP3
```

但是这样会报错，因为obd找不到这个版本：
```
[ERROR] No such package name: oceanbase-ce, version: V4.2.1_CE_BP3.
```

我现在怎么处理的？

我先去[下载中心](https://www.oceanbase.com/softwarecenter?_gl=1*1wf2a0v*_ga*MTkwMjQ3MzQxNC4xNjYzNjU1MDE1*_ga_T35KTM57DZ*MTcxNTU2NzYyMi4xMTc2LjEuMTcxNTU2ODA5Ny42MC4wLjA.)找到这个版本的release note，在release note中可以看到版本 4.2.1.3，然后再去创建demo集群。

**Comment by gys-git** [comment]
OBD can use the release to specify a specific release version, such as: obd demo --oceanbase-ce.release=103000032023122818.el7
The release can be obtained in the following ways:

Obtain the release_no from the RN at the open source official website download center and then append the corresponding operating system version, such as .el7, .el8.
Query the release from the remote repository using obd.

![image](https://github.com/oceanbase/obdeploy/assets/31211986/e8bed80d-8ffb-4ec7-b8b0-845ac4ace03e)
![image](https://github.com/oceanbase/obdeploy/assets/31211986/de374a59-8378-458e-b7a3-3bdede8a3f0c)
