### ISSUE TITLE
DNS record of yum.tbsite.net is broken

### ISSUE THREAD

**Issue by lobshunter** [oceanbase/obdeploy#2]
### 1. Minimal reproduce step
sudo yum-config-manager --add-repo http://yum.tbsite.net/mirrors/oceanbase/OceanBase.repo

### 2. What did you expect to see? 
Add repo sucessfully.

### 3. What did you see instead
```
$ sudo yum-config-manager --add-repo http://yum.tbsite.net/mirrors/oceanbase/OceanBase.repo
Loaded plugins: fastestmirror, langpacks
adding repo from: http://yum.tbsite.net/mirrors/oceanbase/OceanBase.repo
grabbing file http://yum.tbsite.net/mirrors/oceanbase/OceanBase.repo to /etc/yum.repos.d/OceanBase.repo
Could not fetch/save url http://yum.tbsite.net/mirrors/oceanbase/OceanBase.repo to file /etc/yum.repos.d/OceanBase.repo: [Errno 14] curl#6 - "Could not resolve host: yum.tbsite.net; Unknown error"
```

`dig yum.tbsite.net` also returns no A record

### 4. Workaround
Use `yum-config-manager --add-repo https://mirrors.aliyun.com/oceanbase/OceanBase.repo` instead.

Maybe fix README or DNS resolution

**Comment by frf12** [comment]
Thanks for your feedback.
