### ISSUE TITLE
使用obd和模板文件可正常创建obproxy，但是访问obproxy时返回结果异常

### ISSUE THREAD

**Issue by Devin-Wang-haha** [oceanbase/obdeploy#20]
![image](https://user-images.githubusercontent.com/40712460/124957902-294d4c00-e04c-11eb-84c5-4e7e51604103.png)

配置文件如下：
user:
  username: root
  password: 123456
oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 172.17.103.212
  global:
    home_path: /root/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: eth0
    mysql_port: 2881
    rpc_port: 2882
    zone: zone1
    # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.
    memory_limit: 64G
    datafile_disk_percentage: 20
    syslog_level: INFO
    enable_syslog_recycle: true
    max_syslog_file_count: 4
    cluster_id: 3
    # observer cluster name, consistent with obproxy's cluster_name
    appname: single_with_proxy
    root_password: # root user password, can be empty
    proxyro_password: # proxyro user pasword, consistent with obproxy's observer_sys_password, can be empty
obproxy:
  servers:
    - 172.17.103.212
  global:
    listen_port: 2883
    prometheus_listen_port: 2884
    home_path: /root/obproxy
    # oceanbase root server list
    # format: ip:mysql_port,ip:mysql_port
    rs_list: 172.17.103.212:2881
    enable_cluster_checkout: false
    # observer cluster name, consistent with oceanbase-ce's appname
    cluster_name: single_with_proxy
    obproxy_sys_password: # obproxy sys user password, can be empty
    observer_sys_password: # proxyro user pasword, consistent with oceanbase-ce's proxyro_password, can be empty

安装过程中的obproxy版本信息如下：
![image](https://user-images.githubusercontent.com/40712460/124958548-da53e680-e04c-11eb-9b9e-6c3886cb525a.png)

麻烦看一下吧，谢谢～

**Comment by Devin-Wang-haha** [comment]
图未贴完，应该可以分成两个问题，一个是oceanbase-ce的proxyro_password配置项除了需要与obproxy的observer_sys_password的配置项相同外，还必须不能为空，为空时会出错，二是proxysys登录obproxy后show database显示的东西很奇怪，SHOW proxyconfig可以正常显示

**Comment by frf12** [comment]
感谢反馈。目前proxyro_password不能为空。如果不想设置proxyro的密码，可以把proxyro_password的配置注释或者删除。
我们将在最近的更新中修复。

-uroot@proxysys登录的是obproxy的管理员用户。这个并非传统的数据库用户。

**Comment by frf12** [comment]
fix #30

**Comment by longletian** [comment]
![image](https://user-images.githubusercontent.com/28197668/129321104-9c0939e6-31b4-4c66-a9fc-7b86472770cb.png)
user:
  username: root
  password: root
oceanbase-ce:
  servers:
    - name: z1
      # Please don't use hostname, only IP can be supported
      ip: 192.168.106.129
  global:
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: ens33
    # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.
    memory_limit: 64G
    datafile_disk_percentage: 20
    syslog_level: INFO
    enable_syslog_recycle: true
    max_syslog_file_count: 4
    cluster_id: 1
    # observer cluster name, consistent with obproxy's cluster_name
    appname: ob_cluster
    # root_password: # root user password, can be empty
    # proxyro_password: # proxyro user pasword, consistent with obproxy's observer_sys_password, can be empty
  # In this example , support multiple ob process in single node, so different process use different ports.
  # If deploy ob cluster in multiple nodes, the port and path setting can be same.
  z1:
    mysql_port: 2881
    rpc_port: 2882
    home_path: /root/observer1
    zone: zone1
obproxy:
  servers:
    - 192.168.106.129
  global:
    listen_port: 2883
    prometheus_listen_port: 2884
    home_path: /root/obproxy
    # oceanbase root server list
    # format: ip:mysql_port,ip:mysql_port
    rs_list: 192.168.106.129:2881
    enable_cluster_checkout: false
    # observer cluster name, consistent with oceanbase-ce's appname
    cluster_name: ob_cluster
    obproxy_sys_password: root
    # observer_sys_password: # proxyro user pasword, consistent with oceanbase-ce's proxyro_password, can be empty
老哥 为什么我会报连接失败
