### ISSUE TITLE
[Bug]: complile obd web,  after starting, occur undefine err

### ISSUE THREAD

**Issue by PanternBao** [oceanbase/obdeploy#200]
### Describe the bug

compile obd web  manually, in google chroom, enter：http://localhost:8000 

occur undefine err

### Environment

linux version：3.10.0-862.14.4.el7.x86_64

os version：CentOS Linux release 7.5.1804 (Core)

yarn version: 1.22.22

### Fast reproduce steps

cd web
yarn
yarn start

in google chrom，enter：http://localhost:8000

### Expected behavior

no error

### Actual behavior

![image](https://github.com/oceanbase/obdeploy/assets/21034841/2f4ac288-04bf-406e-9223-b7dd6db61069)

**Comment by yang1666204** [comment]
Please check if `node_modules` is in the web directory. If so, try deleting `node_modules` and try again. Then please provide the `Node` version. I am trying to reproduce.

**Comment by PanternBao** [comment]
> Please check if `node_modules` is in the web directory. If so, try deleting `node_modules` and try again. Then please provide the `Node` version. I am trying to reproduce.

thanks, I followed your plan, but I still reproduce the error.

`Node` version:
```
$ node -v
v16.20.2
```

**Comment by yang1666204** [comment]
I found two files named app. Try deleting `app.ts`.

**Comment by PanternBao** [comment]
> I found two files named app. Try deleting `app.ts`.

thanks, it works.

**Comment by yang1666204** [comment]
OK, we will resolve this issue as soon as possible. And let we know if you have any questions or if I can help with anything else.

**Comment by PanternBao** [comment]
> OK, we will resolve this issue as soon as possible. And let we know if you have any questions or if I can help with anything else.

Thanks. There are no other questions at the moment. If there are any questions, I will raise an issue.

**Comment by gys-git** [comment]
https://github.com/oceanbase/obdeploy/pull/201
