### ISSUE TITLE
离线安装执行obd cluster deploy时, 会请求阿里云下载repomd.xml文件

### ISSUE THREAD

**Issue by zh0122** [oceanbase/obdeploy#22]
**离线环境**
按照官方文档quick-start配置好 yaml文件后,
已执行 `obd mirror clone *.rpm`
版本: 
ob-deploy-1.0.2-2.el7.x86_64.rpm
obproxy-3.1.0-1.el7.x86_64.rpm
oceanbase-ce-3.1.0-2.el7.x86_64.rpm
oceanbase-ce-libs-3.1.0-2.el7.x86_64.rpm

执行`obd cluster deploy` 后,  会卡在 `Update OceanBase-community-stable-el7 -` 不动,  
![image](https://user-images.githubusercontent.com/4396287/125925501-fbe4d2b3-86d4-4107-b4f7-cc374cbfa2b9.png)

执行 `netstat -nalp  | grep obd` , 会看到尝试连接外网, 并且会轮询不同的IP
![image](https://user-images.githubusercontent.com/4396287/125925556-70a8de20-f787-4ac3-9ad2-3614ece63079.png)

在deploy 界面执行 ctrl + C后, 会报如下错误, 可以看到是在请求阿里云
![image](https://user-images.githubusercontent.com/4396287/125925713-2628acc8-8b23-4381-9c72-0efcf85f4ac3.png)

**希望可以开启完全离线部署模式**

**Comment by frf12** [comment]
感谢反馈，我们会在后续的更新中优化。
目前您可以使用手动删除远程镜像仓库配置文件的方式避免此问题，命令：`rm ~/.obd/mirror/remote/*.repo`

**Comment by frf12** [comment]
可以更新到1.2.0以上的版本使用`obd mirror disable remote`关闭远程仓库
