### ISSUE TITLE
No such net interface: enp1s0 caused by line 170 of start_check.py

### ISSUE THREAD

**Issue by smallpotato000** [oceanbase/obdeploy#37]
Hardware: E5-2650v2 based kvm virtual machine
OS:openAnolis 8.4GA
Problem:
No such net interface: enp1s0
on all nodes when executing obd cluster start obcluster
Caused by:
line 170 of start_check.py:
if not client.execute_command("grep -e ' %s:' /proc/net/dev" % devname):
the space in grep -e ' %s:' 
in /proc/net/dev, there is no space before enp1s0
removing the space can fix the problem.
Located in /root/.obd/plugins/oceanbase/3.1.0/start_check.py.
perhaps the same problem in /root/.obd/plugins/obproxy/3.1.0/start_check.py should also be fixed?

**Comment by frf12** [comment]
Thank you for your feedback. We will fix it as soon as possible.

If there is only one network device driver except `lo`, you can bypass this bug by removing the `devname` in yaml.
