### ISSUE TITLE
创建tenant 失败

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#39]

**Comment by longdafeng** [comment]
```
admin@obdriver:~$ obd cluster tenant create obtest test
Get local repositories and plugins ok
[WARN] No such create_tenant plugin for obproxy-3.1.0

Open ssh connection ok
Connect to observer ok
Create tenant test x
[ERROR] Tenant test already exists

admin@obdriver:~$ obd cluster tenant create obtest mytest
Get local repositories and plugins ok
[WARN] No such create_tenant plugin for obproxy-3.1.0

Open ssh connection ok
Connect to observer ok
Create tenant test x
[ERROR] Tenant test already exists



admin@obdriver:~$ obclient -hobdriver -P2883 -uroot
Welcome to the OceanBase.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.6.25 OceanBase 3.1.0 (r3-b20901e8c84d3ea774beeaca963c67d7802e4b4e) (Built Aug 10 2021 07:51:04)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show tenants
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near 'tenants' at line 1
MySQL [(none)]> use oceanbase;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [oceanbase]> show tenants;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near 'tenants' at line 1
MySQL [oceanbase]> show tenant;
+---------------------+
| Current_tenant_name |
+---------------------+
| sys                 |
+---------------------+
1 row in set (0.001 sec)

MySQL [oceanbase]> SELECT sum(c.max_cpu), sum(c.max_memory) FROM __all_resource_pool as a, __all_unit_config AS c WHERE a.unit_config_id=c.unit_config_id;
+----------------+-------------------+
| sum(c.max_cpu) | sum(c.max_memory) |
+----------------+-------------------+
|             14 |      140660178944 |
+----------------+-------------------+
1 row in set (0.005 sec)

MySQL [oceanbase]> +----------------+-------------------+
    -> | sum(c.max_cpu) | sum(c.max_memory) |
    -> +----------------+-------------------+
    -> |              5 |       17179869184 |
    -> +----------------+-------------------+
    -> 1 row in set (0.00 sec)
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '+----------------+-------------------+
| sum(c.max_cpu) | sum(c.max_memory) |
+-' at line 1
MySQL [oceanbase]> exit
Bye
```

**Comment by longdafeng** [comment]
问题应该出现在 show tenant;  为什么show tenant 显示不出tenant, 而select * from gv$tenant 可以显示

```
ySQL [oceanbase]> select * from gv$unit;
+---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
| unit_id | unit_config_id | unit_config_name | resource_pool_id | resource_pool_name | zone  | tenant_id | tenant_name | svr_ip        | svr_port | migrate_from_svr_ip | migrate_from_svr_port | max_cpu | min_cpu | max_memory   | min_memory   | max_iops | min_iops | max_disk_size | max_session_num     |
+---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
|       1 |              1 | sys_unit_config  |                1 | sys_pool           | zone1 |         1 | sys         | 172.30.62.200 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
|       2 |              1 | sys_unit_config  |                1 | sys_pool           | zone2 |         1 | sys         | 172.30.62.201 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
|       3 |              1 | sys_unit_config  |                1 | sys_pool           | zone3 |         1 | sys         | 172.30.62.202 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
|    1001 |           1001 | test_unit        |             1001 | test_pool          | zone1 |      1001 | test        | 172.30.62.200 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
|    1002 |           1001 | test_unit        |             1001 | test_pool          | zone2 |      1001 | test        | 172.30.62.201 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
|    1003 |           1001 | test_unit        |             1001 | test_pool          | zone3 |      1001 | test        | 172.30.62.202 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
+---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
6 rows in set (0.01 sec)

MySQL [oceanbase]> select * from gv$tenant;
+-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
| tenant_id | tenant_name | zone_list         | primary_zone      | collation_type | info          | read_only | locality                                    |
+-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
|         1 | sys         | zone1;zone2;zone3 | zone1;zone2,zone3 |              0 | system tenant |         0 | FULL{1}@zone1, FULL{1}@zone2, FULL{1}@zone3 |
|      1001 | test        | zone1;zone2;zone3 | RANDOM            |              0 |               |         0 | FULL{1}@zone1, FULL{1}@zone2, FULL{1}@zone3 |
+-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
2 rows in set (0.01 sec)

MySQL [oceanbase]> show tenant;
+---------------------+
| Current_tenant_name |
+---------------------+
| sys                 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by askdb** [comment]
> 问题应该出现在 show tenant; 为什么show tenant 显示不出tenant, 而select * from gv$tenant 可以显示
> 
> ```
> ySQL [oceanbase]> select * from gv$unit;
> +---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
> | unit_id | unit_config_id | unit_config_name | resource_pool_id | resource_pool_name | zone  | tenant_id | tenant_name | svr_ip        | svr_port | migrate_from_svr_ip | migrate_from_svr_port | max_cpu | min_cpu | max_memory   | min_memory   | max_iops | min_iops | max_disk_size | max_session_num     |
> +---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
> |       1 |              1 | sys_unit_config  |                1 | sys_pool           | zone1 |         1 | sys         | 172.30.62.200 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
> |       2 |              1 | sys_unit_config  |                1 | sys_pool           | zone2 |         1 | sys         | 172.30.62.201 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
> |       3 |              1 | sys_unit_config  |                1 | sys_pool           | zone3 |         1 | sys         | 172.30.62.202 |     2882 |                     |                     0 |       5 |     2.5 |  17179869184 |  12884901888 |    10000 |     5000 |  801011400704 | 9223372036854775807 |
> |    1001 |           1001 | test_unit        |             1001 | test_pool          | zone1 |      1001 | test        | 172.30.62.200 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
> |    1002 |           1001 | test_unit        |             1001 | test_pool          | zone2 |      1001 | test        | 172.30.62.201 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
> |    1003 |           1001 | test_unit        |             1001 | test_pool          | zone3 |      1001 | test        | 172.30.62.202 |     2882 |                     |                     0 |       9 |       9 | 123480309760 | 123480309760 |      128 |      128 |  801011400704 |                  64 |
> +---------+----------------+------------------+------------------+--------------------+-------+-----------+-------------+---------------+----------+---------------------+-----------------------+---------+---------+--------------+--------------+----------+----------+---------------+---------------------+
> 6 rows in set (0.01 sec)
> 
> MySQL [oceanbase]> select * from gv$tenant;
> +-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
> | tenant_id | tenant_name | zone_list         | primary_zone      | collation_type | info          | read_only | locality                                    |
> +-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
> |         1 | sys         | zone1;zone2;zone3 | zone1;zone2,zone3 |              0 | system tenant |         0 | FULL{1}@zone1, FULL{1}@zone2, FULL{1}@zone3 |
> |      1001 | test        | zone1;zone2;zone3 | RANDOM            |              0 |               |         0 | FULL{1}@zone1, FULL{1}@zone2, FULL{1}@zone3 |
> +-----------+-------------+-------------------+-------------------+----------------+---------------+-----------+---------------------------------------------+
> 2 rows in set (0.01 sec)
> 
> MySQL [oceanbase]> show tenant;
> +---------------------+
> | Current_tenant_name |
> +---------------------+
> | sys                 |
> +---------------------+
> 1 row in set (0.00 sec)
> ```

show tenant 只能显式当前登录的租户名，
可以使用obd命令中创建的普通租户登录后再执行show tenant；
