### ISSUE TITLE
autodeploy 没有探测远程的机器配置

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#41]
autodeploy 探测的是本机的硬件配置, 不是探测的真正observer 上机器的配置

当主控机器和observer 机器配置出入比较大时, 会有很大的偏差

**Comment by longdafeng** [comment]
探测了内存, 但没有探测cpu

**Comment by frf12** [comment]
获取cpu数的方法为[plugins/oceanbase/3.1.0/generate_config.py#L171](https://github.com/oceanbase/obdeploy/blob/master/plugins/oceanbase/3.1.0/generate_config.py#L171)
```python
            ret = client.execute_command("grep -e 'processor\s*:' /proc/cpuinfo | wc -l")
```
使用了远程客户端，获取到的应该是远程的。能否提供配置及带-v的执行日志呢？

**Comment by longdafeng** [comment]
Fixed in 1.4
