### ISSUE TITLE
ubuntu 18.04源码编译obdeploy报错 fatal: 不是一个 git 仓库（或者任何父目录）：.git

### ISSUE THREAD

**Issue by imbawenzi** [oceanbase/obdeploy#65]
\> sh build.sh
build.sh: 9: build.sh: Bad substitution
\> bash build.sh
Enter python path [default /usr/bin/python2.7-config]:/usr/bin/python3.8
--2021-12-21 17:08:59--  https://mirrors.aliyun.com/oceanbase/OceanBase.repo
正在连接 127.0.0.1:8889... 已连接。
已发出 Proxy 请求，正在等待回应... 200 OK
长度： 512 [application/octet-stream]
正在保存至: “OceanBase.repo”

OceanBase.repo                     100%[================================================================>]     512  --.-KB/s    用时 0s    

2021-12-21 17:08:59 (302 MB/s) - 已保存 “OceanBase.repo” [512/512])

fatal: 不是一个 git 仓库（或者任何父目录）：.git
fatal: 不是一个 git 仓库（或者任何父目录）：.git
Installation of obd finished successfully
Please source /etc/profile.d/obd.sh to enable it

**Comment by frf12** [comment]
源码安装需要目录是一个git仓库，我们需要通过git命令获取到commit id
