### ISSUE TITLE
默认分布式部署文件缺少机器网卡配置项

### ISSUE THREAD

**Issue by ghostmickey** [oceanbase/obdeploy#68]
使用github/gitee中提供的默认的distributed-with-obproxy-example.yaml进行部署时，启动报错：
[ERROR] server3(x.x.x.x) lo fail to ping x.x.x.x. Please check configuration `devname`
[ERROR] server3(x.x.x.x) lo fail to ping x.x.x.x. Please check configuration `devname`
[ERROR] server3(x.x.x.x) lo fail to ping x.x.x.x. Please check configuration `devname`
调研后发现，需要在yaml的各个server配置项下增加devname: ethx来指定使用的网卡。
由于配置文件中默认没有给出此配置项，且错误信息给的不是很明确，导致部署失败时无法通过错误信息快速定位，建议在默认的yaml文件中给出此配置项，并附说明此项需要修改为目标机器的网卡名称。

**Comment by frf12** [comment]
感谢反馈。example/autodeploy/distributed-with-obproxy-example.yaml确实不是包含devname。这是用于autodeploy的模板，通常情况下autodeploy会自动识别网卡。example/distributed-with-obproxy-example.yaml中包含devname项。我们后续会在example/autodeploy/distributed-with-obproxy-example.yaml也添加devname的相关说明
