### ISSUE TITLE
3.1.0升级3.1.2报错

### ISSUE THREAD

**Issue by LINxiansheng** [oceanbase/obdeploy#74]
`obd cluster upgrade s1 -V 3.1.2 -v`
![234D6E38-5249-4896-8DC8-1C0F82BF4B07](https://user-images.githubusercontent.com/18351861/147817198-f5a4eb9f-3b31-44cb-b37f-30583f28d66c.png)

**Comment by frf12** [comment]
设置下```shell
export LANG=en_US.UTF-8
```再试试
