### ISSUE TITLE
observer 的root带密码的时候用obd测试跑不过

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/obdeploy#80]

**Comment by frf12** [comment]
如果你的配置中包含了obproxy，那么sysbench测试的时候会优先选择obproxy进行,这种情况下有可能会因为obproxy组件配置中没有observer的root的密码导致链接失败。此时可以在obproxy的global中添加observer_root_password配置用于设置observer root的密码，也可以为obproxy添加depedns显示的将obproxy和observer的配置关联起来。
