### ISSUE TITLE
在256 core 机器上出现bootstrap

### ISSUE THREAD

**Issue by cyberspicecai** [oceanbase/obdeploy#82]
Hi， Guys

when I use the obd deploy the 3-host(128 cores-80 cores-256 cores configuration) cluster. and find bootstrap fail, but another  3-host cluster with 128 cores-80 cores-128 cores configuration are ok.

I think there is a bug, right?

OS:CentOS Linux release 8.5.2111
OceanBase Deploy: 1.2.1
obd  repo list
 name                    | version | release               | arch   | md5          | tags              |
| oceanbase-ce      | 3.1.2   | 20220107080856        | x86_64 | 2990cadae31deb337c20aee26d74834c         | obv312            |
| oceanbase-ce      | 3.1.2   | 10000392021123010.el8 | x86_64 | 0005ef8ee805db0f6b4c493c9eead69bdb78ef00 | oceanbase-ce      |
| oceanbase-ce-libs | 3.1.2   | 10000392021123010.el8 | x86_64 | 87dcfcbaa952874ae41333ab9ba46ff110d5ea70 | oceanbase-ce-libs |

***********************************************8
How to replay/REDO:
1,  Deploy one cluster xxxx with at least one 256-core host by OBD
2, Just obd cluster start xxxx.
*************************************************
the clust configuration -yaml:
## Only need to configure when remote login is required
# user:
#   username: your username
#   password: your password if need
#   key_file: your ssh-key file path if need
#   port: your ssh port, default 22
#   timeout: ssh connection timeout (second), default 30
oceanbase-ce:
  servers:
    - name: z1
      # Please don't use hostname, only IP can be supported
      ip: 192.168.1.174
    - name: z2
      ip: 192.168.1.114
    - name: z3
      ip: 192.168.1.112
  
  global:
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    #devname: ens3
    # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.
    memory_limit: 160G # The maximum running memory for an observer
    # The reserved system memory. system_memory is reserved for general tenants. The default value is 30G.
    # system_memory: 30G
    datafile_disk_percentage: 30 # The percentage of the data_dir space to the total disk space. This value takes effect only when datafile_size is 0. The default value is 90.
    syslog_level: INFO # System log level. The default value is INFO.
    enable_syslog_wf: false # Print system logs whose levels are higher than WARNING to a separate log file. The default value is true.
    enable_syslog_recycle: true # Enable auto system log recycling or not. The default value is false.
    max_syslog_file_count: 4 # The maximum number of reserved log files before enabling auto recycling. The default value is 0.
    # root_password: # root user password
  # In this example , support multiple ob process in single node, so different process use different ports.
  # If deploy ob cluster in multiple nodes, the port and path setting can be same. 
  z1:
    mysql_port: 2881 # External port for OceanBase Database. The default value is 2881.
    rpc_port: 2882 # Internal port for OceanBase Database. The default value is 2882.
    devname: ens72f1
    # The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.
    home_path: /data/xxxxob
    # The directory for data storage. The default value is $home_path/store.
    # data_dir: /data
    # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
    # redo_dir: /redo
    zone: zone1
  z2:
    mysql_port: 2881 # External port for OceanBase Database. The default value is 2881.
    rpc_port: 2882 # Internal port for OceanBase Database. The default value is 2882.
    devname: enp65s0f0
    #  The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.
    home_path: /data/amdob
    # The directory for data storage. The default value is $home_path/store.
    # data_dir: /data
    # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
    # redo_dir: /redo
    zone: zone2
  z3:
    mysql_port: 2881 # External port for OceanBase Database. The default value is 2881.
    rpc_port: 2882 # Internal port for OceanBase Database. The default value is 2882.
    devname: ens3f0
    #  The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.
    home_path: /data/intelob
    # The directory for data storage. The default value is $home_path/store.
    # data_dir: /data
    # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
    # redo_dir: /redo
    zone: zone3
**********************************
the log:
Vim: Warning: Output is not to a terminal

  [36mglobal[m[35m:[m
   [34m # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
[m   [34m # if set severs as "127.0.0.1", please set devname as "lo"
[m   [34m # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
[m   [34m #devname: ens3
[m   [34m # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.[m
    [36mmemory_limit[m[35m:[m 160G[34m # The maximum running memory for an observer
[m   [34m # The reserved system memory. system_memory is reserved for general tenants. The default value is 30G.
[m   [34m # system_memory: 30G[m
    [36mdatafile_disk_percentage[m[35m:[m [31m30[m[34m # The percentage of the data_dir space to the total disk space. This value takes effect only when datafile_size is 0. The default value is 90.[m
    [36msyslog_level[m[35m:[m INFO[34m # System log level. The default value is INFO.[m
    [36menable_syslog_wf[m[35m:[m [31mfalse[m[34m # Print system logs whose levels are higher than WARNING to a separate log file. The default value is true.[m
    [36menable_syslog_recycle[m[35m:[m [31mtrue[m[34m # Enable auto system log recycling or not. The default value is false.[m
    [36mmax_syslog_file_count[m[35m:[m [31m4[m[34m # The maximum number of reserved log files before enabling auto recycling. The default value is 0.
[m   [34m # root_password: # root user password
[m [34m # In this example , support multiple ob process in single node, so different process use different ports.
[m [34m # If deploy ob cluster in multiple nodes, the port and path setting can be same. [m
  [36mz1[m[35m:[m
    [36mmysql_port[m[35m:[m [31m2881[m[34m # External port for OceanBase Database. The default value is 2881.[m
    [36mrpc_port[m[35m:[m [31m2882[m[34m # Internal port for OceanBase Database. The default value is 2882.[m
    [36mdevname[m[35m:[m ens72f1
   [34m # The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.[m
    [36mhome_path[m[35m:[m /data/xxxxob
   [34m # The directory for data storage. The default value is $home_path/store.
[m   [34m # data_dir: /data
[m   [34m # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
[m   [34m # redo_dir: /redo[m
    [36mzone[m[35m:[m zone1
  [36mz2[m[35m:[m
    [36mmysql_port[m[35m:[m [31m2881[m[34m # External port for OceanBase Database. The default value is 2881.[m
    [36mrpc_port[m[35m:[m [31m2882[m[34m # Internal port for OceanBase Database. The default value is 2882.[m
    [36mdevname[m[35m:[m enp65s0f0
   [34m #  The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.[m
    [36mhome_path[m[35m:[m /data/amdob
   [34m # The directory for data storage. The default value is $home_path/store.
[m   [34m # data_dir: /data
[m   [34m # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
[m   [34m # redo_dir: /redo[m
    [36mzone[m[35m:[m zone2
  [36mz3[m[35m:[m
    [36mmysql_port[m[35m:[m [31m2881[m[34m # External port for OceanBase Database. The default value is 2881.[m
    [36mrpc_port[m[35m:[m [31m2882[m[34m # Internal port for OceanBase Database. The default value is 2882.[m
    [36mdevname[m[35m:[m ens3f0
   [34m #  The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.[m
    [36mhome_path[m[35m:[m /data/intelob
   [34m # The directory for data storage. The default value is $home_path/store.
[m   [34m # data_dir: /data
[m   [34m # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
[m   [34m # redo_dir: /redo[m
    [36mzone[m[35m:[m zone3[66;171H71,15[9CBot[65;15H[?25h[?25l[66;161H:[65;15H[66;1H[K[66;1H:[?2004h[?25hq[?25l[?25h
[?25l[?2004l[66;1H[K[66;1H[?2004l[?1l>[?25h[?1049l[23;0;0t- open /root/.obd/version for a+
- mkdir /root/.obd/lock/
- try to get share lock /root/.obd/lock/global
- share lock `/root/.obd/lock/global`, count 1
- cmd: ['xxxx_intel_amd10']
- opts: {'servers': None, 'components': None, 'force_delete': None, 'strict_check': None, 'without_parameter': None}
- Get Deploy by name
- mkdir /root/.obd/cluster/
- try to get exclusive lock /root/.obd/lock/deploy_xxxx_intel_amd10
- exclusive lock `/root/.obd/lock/deploy_xxxx_intel_amd10`, count 1
- Deploy status judge
- Get deploy config
Get local repositories and plugins ok
- mkdir /root/.obd/repository
- Get local repository oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- try to get share lock /root/.obd/lock/mirror_and_repo
- share lock `/root/.obd/lock/mirror_and_repo`, count 1
- mkdir /root/.obd/repository/oceanbase-ce
- Searching start_check plugin for components ...
- Searching start_check plugin for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- mkdir /root/.obd/plugins
- Found for oceanbase-ce-py_script_start_check-3.1.0 for oceanbase-ce-3.1.2
- Searching start plugin for components ...
- Searching start plugin for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- Found for oceanbase-ce-py_script_start-3.1.0 for oceanbase-ce-3.1.2
- Searching connect plugin for components ...
- Searching connect plugin for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- Found for oceanbase-ce-py_script_connect-3.1.0 for oceanbase-ce-3.1.2
- Searching bootstrap plugin for components ...
- Searching bootstrap plugin for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- Found for oceanbase-ce-py_script_bootstrap-3.1.0 for oceanbase-ce-3.1.2
- Searching display plugin for components ...
- Searching display plugin for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- Found for oceanbase-ce-py_script_display-3.1.0 for oceanbase-ce-3.1.2

Open ssh connection ok
Load cluster param plugin ok
- Searching param plugin for components ...
- Search param plugin for oceanbase-ce
- Found for oceanbase-ce-param-3.1.0 for oceanbase-ce-3.1.2
- Applying oceanbase-ce-param-3.1.0 for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00

- Call oceanbase-ce-py_script_start_check-3.1.0 for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- import start_check
- add start_check ref count to 1
Check before start observer ok
-- root@192.168.1.174 execute: cat /data/xxxxob/run/observer.pid -- exited code 1, error output:
cat: /data/xxxxob/run/observer.pid: No such file or directory

-- z1(192.168.1.174) port check
-- root@192.168.1.174 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B41' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.174 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B42' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.174 execute: ls /data/xxxxob/store/sstable/block_file -- exited code 0
-- root@192.168.1.114 execute: cat /data/amdob/run/observer.pid -- exited code 1, error output:
cat: /data/amdob/run/observer.pid: No such file or directory

-- z2(192.168.1.114) port check
-- root@192.168.1.114 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B41' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.114 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B42' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.114 execute: ls /data/amdob/store/sstable/block_file -- exited code 0
-- root@192.168.1.112 execute: cat /data/intelob/run/observer.pid -- exited code 1, error output:
cat: /data/intelob/run/observer.pid: No such file or directory

-- z3(192.168.1.112) port check
-- root@192.168.1.112 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B41' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.112 execute: bash -c 'cat /proc/net/{tcp,udp}' | awk -F' ' '{print $2,$10}' | grep '00000000:0B42' | awk -F' ' '{print $2}' | uniq -- exited code 0
-- root@192.168.1.112 execute: ls /data/intelob/store/sstable/block_file -- exited code 0
-- root@192.168.1.174 execute: cat /proc/sys/fs/aio-max-nr /proc/sys/fs/aio-nr -- exited code 0
-- root@192.168.1.174 execute: ulimit -n -- exited code 0
-- root@192.168.1.174 execute: cat /proc/meminfo -- exited code 0
-- root@192.168.1.174 execute: df --block-size=1024 -- exited code 0
-- disk: {'/': {'total': 3989277446144, 'avail': 3612209303552, 'need': 0, 'threshold': 2}, '/dev': {'total': 270287323136, 'avail': 270287323136, 'need': 0, 'threshold': 2}, '/dev/shm': {'total': 270315888640, 'avail': 270315888640, 'need': 0, 'threshold': 2}, '/run': {'total': 270315888640, 'avail': 270296506368, 'need': 0, 'threshold': 2}, '/sys/fs/cgroup': {'total': 270315888640, 'avail': 270315888640, 'need': 0, 'threshold': 2}, '/boot': {'total': 1023303680, 'avail': 460541952, 'need': 0, 'threshold': 2}, '/run/user/42': {'total': 54063177728, 'avail': 54063161344, 'need': 0, 'threshold': 2}, '/run/user/0': {'total': 54063177728, 'avail': 54063177728, 'need': 0, 'threshold': 2}, '/data': {'total': 1575068344320, 'avail': 497190289408, 'need': 0, 'threshold': 2}}
-- root@192.168.1.114 execute: cat /proc/sys/fs/aio-max-nr /proc/sys/fs/aio-nr -- exited code 0
-- root@192.168.1.114 execute: ulimit -n -- exited code 0
-- root@192.168.1.114 execute: cat /proc/meminfo -- exited code 0
-- root@192.168.1.114 execute: df --block-size=1024 -- exited code 0
-- disk: {'/': {'total': 75125227520, 'avail': 67840217088, 'need': 0, 'threshold': 2}, '/dev': {'total': 118053625856, 'avail': 118053625856, 'need': 0, 'threshold': 2}, '/dev/shm': {'total': 118082760704, 'avail': 118082760704, 'need': 0, 'threshold': 2}, '/run': {'total': 118082760704, 'avail': 118062694400, 'need': 0, 'threshold': 2}, '/sys/fs/cgroup': {'total': 118082760704, 'avail': 118082760704, 'need': 0, 'threshold': 2}, '/boot': {'total': 1063256064, 'avail': 624144384, 'need': 0, 'threshold': 2}, '/home': {'total': 3917710397440, 'avail': 3868386504704, 'need': 0, 'threshold': 2}, '/run/user/0': {'total': 23616548864, 'avail': 23616495616, 'need': 0, 'threshold': 2}, '/data': {'total': 1599539908608, 'avail': 560329302016, 'need': 0, 'threshold': 2}}
-- root@192.168.1.112 execute: cat /proc/sys/fs/aio-max-nr /proc/sys/fs/aio-nr -- exited code 0
-- root@192.168.1.112 execute: ulimit -n -- exited code 0
-- root@192.168.1.112 execute: cat /proc/meminfo -- exited code 0
-- root@192.168.1.112 execute: df --block-size=1024 -- exited code 0
-- disk: {'/': {'total': 75125227520, 'avail': 58658381824, 'need': 0, 'threshold': 2}, '/dev': {'total': 202001055744, 'avail': 202001055744, 'need': 0, 'threshold': 2}, '/dev/shm': {'total': 202031288320, 'avail': 202031288320, 'need': 0, 'threshold': 2}, '/run': {'total': 202031288320, 'avail': 201994788864, 'need': 0, 'threshold': 2}, '/sys/fs/cgroup': {'total': 202031288320, 'avail': 202031288320, 'need': 0, 'threshold': 2}, '/boot': {'total': 1063256064, 'avail': 697192448, 'need': 0, 'threshold': 2}, '/home': {'total': 399375269888, 'avail': 396548882432, 'need': 0, 'threshold': 2}, '/run/user/0': {'total': 40406257664, 'avail': 40406220800, 'need': 0, 'threshold': 2}, '/data': {'total': 1575068344320, 'avail': 677431332864, 'need': 0, 'threshold': 2}}
-- root@192.168.1.174 execute: date +%s%N -- exited code 0
-- 192.168.1.174 time delta -1.206787109375
-- root@192.168.1.114 execute: date +%s%N -- exited code 0
-- 192.168.1.114 time delta -0.87451171875
-- root@192.168.1.112 execute: date +%s%N -- exited code 0
-- 192.168.1.112 time delta -0.5009765625

- sub start_check ref count to 0
- export start_check
- Call oceanbase-ce-py_script_start-3.1.0 for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- import start
- add start ref count to 1
Start observer ok
-- root@192.168.1.174 execute: bash -c 'if [ -f /data/xxxxob/bin/observer ]; then exit 1; else exit 0; fi;' -- exited code 1, error output:

-- root@192.168.1.174 execute: ls /data/xxxxob/store/ilog/ -- exited code 0
-- root@192.168.1.174 execute: cat /data/xxxxob/run/observer.pid -- exited code 1, error output:
cat: /data/xxxxob/run/observer.pid: No such file or directory

-- z1(192.168.1.174) start command construction
-- root@192.168.1.114 execute: bash -c 'if [ -f /data/amdob/bin/observer ]; then exit 1; else exit 0; fi;' -- exited code 1, error output:

-- root@192.168.1.114 execute: ls /data/amdob/store/ilog/ -- exited code 0
-- root@192.168.1.114 execute: cat /data/amdob/run/observer.pid -- exited code 1, error output:
cat: /data/amdob/run/observer.pid: No such file or directory

-- z2(192.168.1.114) start command construction
-- root@192.168.1.112 execute: bash -c 'if [ -f /data/intelob/bin/observer ]; then exit 1; else exit 0; fi;' -- exited code 1, error output:

-- root@192.168.1.112 execute: ls /data/intelob/store/ilog/ -- exited code 0
-- root@192.168.1.112 execute: cat /data/intelob/run/observer.pid -- exited code 1, error output:
cat: /data/intelob/run/observer.pid: No such file or directory

-- z3(192.168.1.112) start command construction
-- starting z1(192.168.1.174) observer
-- root@192.168.1.174 set env LD_LIBRARY_PATH to '/data/xxxxob/lib:'
-- root@192.168.1.174 execute: cd /data/xxxxob; /data/xxxxob/bin/observer -r '192.168.1.174:2882:2881;192.168.1.114:2882:2881;192.168.1.112:2882:2881' -o __min_full_resource_pool_memory=268435456,memory_limit='160G',datafile_disk_percentage=30,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4 -z 'zone1' -p 2881 -P 2882 -c 1 -d '/data/xxxxob/store' -i 'ens72f1' -l 'INFO' -- exited code 0
-- root@192.168.1.174 set env LD_LIBRARY_PATH to ''
-- starting z2(192.168.1.114) observer
-- root@192.168.1.114 set env LD_LIBRARY_PATH to '/data/amdob/lib:'
-- root@192.168.1.114 execute: cd /data/amdob; /data/amdob/bin/observer -r '192.168.1.174:2882:2881;192.168.1.114:2882:2881;192.168.1.112:2882:2881' -o __min_full_resource_pool_memory=268435456,memory_limit='160G',datafile_disk_percentage=30,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4 -z 'zone2' -p 2881 -P 2882 -c 1 -d '/data/amdob/store' -i 'enp65s0f0' -l 'INFO' -- exited code 0
-- root@192.168.1.114 set env LD_LIBRARY_PATH to ''
-- starting z3(192.168.1.112) observer
-- root@192.168.1.112 set env LD_LIBRARY_PATH to '/data/intelob/lib:'
-- root@192.168.1.112 execute: cd /data/intelob; /data/intelob/bin/observer -r '192.168.1.174:2882:2881;192.168.1.114:2882:2881;192.168.1.112:2882:2881' -o __min_full_resource_pool_memory=268435456,memory_limit='160G',datafile_disk_percentage=30,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4 -z 'zone3' -p 2881 -P 2882 -c 1 -d '/data/intelob/store' -i 'ens3f0' -l 'INFO' -- exited code 0
-- root@192.168.1.112 set env LD_LIBRARY_PATH to ''

observer program health check ok
-- z1(192.168.1.174) program health check
-- root@192.168.1.174 execute: cat /data/xxxxob/run/observer.pid -- exited code 0
-- root@192.168.1.174 execute: ls /proc/132439 -- exited code 0
-- z1(192.168.1.174) observer[pid: 132439] started
-- z2(192.168.1.114) program health check
-- root@192.168.1.114 execute: cat /data/amdob/run/observer.pid -- exited code 0
-- root@192.168.1.114 execute: ls /proc/22872 -- exited code 0
-- z2(192.168.1.114) observer[pid: 22872] started
-- z3(192.168.1.112) program health check
-- root@192.168.1.112 execute: cat /data/intelob/run/observer.pid -- exited code 0
-- root@192.168.1.112 execute: ls /proc/1113311 -- exited code 0
-- z3(192.168.1.112) observer[pid: 1113311] started

- sub start ref count to 0
- export start
- Call oceanbase-ce-py_script_connect-3.1.0 for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- import connect
- add connect ref count to 1
Connect to observer ok
-- connect 192.168.1.174 -P2881 -uroot -p

- sub connect ref count to 0
- export connect
Initialize cluster
- Call oceanbase-ce-py_script_bootstrap-3.1.0 for oceanbase-ce-3.1.2-0005ef8ee805db0f6b4c493c9eead69bdb78ef00
- import bootstrap
- add bootstrap ref count to 1
-- execute sql: set session ob_query_timeout=1000000000
Cluster bootstrap x
-- execute sql: alter system bootstrap REGION "sys_region" ZONE "zone1" SERVER "192.168.1.174:2882",REGION "sys_region" ZONE "zone2" SERVER "192.168.1.114:2882",REGION "sys_region" ZONE "zone3" SERVER "192.168.1.112:2882"
Traceback (most recent call last):
  File "core.py", line 1084, in start_cluster
  File "_plugin.py", line 235, in __call__
    else:
  File "_plugin.py", line 209, in _new_func
    except Exception as e:
  File "/root/.obd/plugins/oceanbase-ce/3.1.0/bootstrap.py", line 46, in bootstrap
    cursor.execute(sql)
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/obd/lib/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/obd/lib/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (4015, 'System error')

Traceback (most recent call last):
  File "/root/.obd/plugins/oceanbase-ce/3.1.0/bootstrap.py", line 46, in bootstrap
    cursor.execute(sql)
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/obd/lib/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/obd/lib/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (4015, 'System error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.py", line 1084, in start_cluster
  File "_plugin.py", line 235, in __call__
    else:
  File "_plugin.py", line 209, in _new_func
    except Exception as e:
  File "/root/.obd/plugins/oceanbase-ce/3.1.0/bootstrap.py", line 70, in bootstrap
    cursor.execute('select * from oceanbase.__all_rootservice_event_history where module = "bootstrap" and event = "bootstrap_succeed"')
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/obd/lib/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/obd/lib/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/obd/lib/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/obd/lib/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'oceanbase.__all_rootservice_event_history' doesn't exist")

- sub bootstrap ref count to 0
- export bootstrap
Cluster init failed
- share lock /root/.obd/lock/mirror_and_repo release, count 0
- unlock /root/.obd/lock/mirror_and_repo
- exclusive lock /root/.obd/lock/deploy_xxxx_intel_amd10 release, count 0
- unlock /root/.obd/lock/deploy_xxxx_intel_amd10
- share lock /root/.obd/lock/global release, count 0
- unlock /root/.obd/lock/global

**Comment by longdafeng** [comment]
1. 你的版本有点老, 你能换一个最新的版本 安装试一下吗 ?   “/root/.obd/plugins/oceanbase-ce/3.1.0/bootstrap.py”

2. 你贴的格式似乎不是很好, 你贴附件或者日志时, 可否用原始的格式 (参考markdown 使用原始code 格式)
```
   
```

**Comment by cyberspicecai** [comment]
企业版ob 有个256 core 的walkaround， 开源版本，需要帮忙出一个。obd是从repo直接直接安装的。

**Comment by cyberspicecai** [comment]
./deps/oblib/src/lib/ob_define.h:1489:const int64_t OB_MAX_THREAD_NUM = 8192;
./deps/oblib/src/lib/ob_define.h:1490://const int64_t OB_MAX_THREAD_NUM = 4096;
与OB的技术人员沟通后，修改OB_MAX_THREAD_NUM 重新编译后就，在部署就OK了。

**Comment by cyberspicecai** [comment]
问题出现OB_MAX_THREAD_NUM设置较小。已经验证。

**Comment by longdafeng** [comment]
收到, 谢谢反馈
