### ISSUE TITLE
Failed to create tenant after reset the root@sys password

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#84]
Testing steps

1. create a cluster
2. set the root@sys 's password
3. create tenant  obd cluster tenant create

Don't know how to input the password 

Suggestion add option -p xxxx, which is same as mysql

**Comment by longdafeng** [comment]
set root@sys by mysql

**Comment by frf12** [comment]
set the root@sys 's password by sql will cause the OBD to be unable to connect to OB. Please reset the password and use `edit-config` to modify the `root_ password` instead of sql.
