### ISSUE TITLE
Don't know how to download obtpch or ob-sysbench

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#86]
it is ok under online mode
```
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://mirrors.aliyun.com/oceanbase/OceanBase.repo
sudo yum install obtpch
```

But it doesn't work under offline mode, 
please upload these package to  the repo in the document  https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.2/instructions-for-downloading-the-installation-package

**Comment by gys-git** [comment]
This issue will be fixed in obd 2.9.0.
