### ISSUE TITLE
Please how long will it take for every step of obtpch

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#89]
Every step will take much time to run, in order to better tuning the performance of system, please add timestamp like this

```
2022-02-10 10:20:04  Begin to send tbl to remote xxx
2022-02-10 10:24:06 Sussessfully sent tbl to remote xxxx

```
Get local repositories and plugins ok
Open ssh connection ok
Cluster status check ok
Connect observer(z1(172.30.62.232):2881) ok
Generate Data (Scale Factor: 10) ok
Send tbl to remote (z1(172.30.62.232)) ok
reate table ok
Load data /
```

**Comment by gys-git** [comment]
Loading data in TPCH takes relatively longer time, which depends on the amount of data and the OceanBase tenant specifications. In the upcoming version of OBD v2.10.0, we support bypassing import, which will significantly reduce the load data time.
