### ISSUE TITLE
obd test should be able to run on the cluster which installed by OCP

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/obdeploy#90]
Right now, obd test can run on the cluster which deployed by OBD, but it can't be run on the cluster which installed by OCP.

In theory, it should be able to run on the cluster which installed by OCP.  Because user has input all user/password information, if obd want to fetch the hardware information, it can directly fetch the information from the database.

**Comment by frf12** [comment]
fixed by #90

**Comment by gys-git** [comment]
OBD v2.9.0 supports taking over a cluster. First, you can take over a non-OBD-deployed cluster, and then perform an OBD test. The documentation is available at: https://www.oceanbase.com/docs/community-obd-cn-1000000000955380.
