### ISSUE TITLE
example/mini-single-example.yaml user部分注释调整

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdeploy#92]
目前是Only need to configure when remote login is required
如果就在obd当前机器，当前用户下 部署一个单节点的OB环境，按照现在的提示，可以不用填写密码或者密钥

实际为：
只有在ip为127.0.0.1，用户为当前用户时才不需要身份校验，其他时候请填写正确的密码或者密钥。

**Comment by gys-git** [comment]
If remote nodes are configured with passwordless login, then you do not need to fill in the password. Leaving the account blank will default to the user who is currently executing the command.
