### ISSUE TITLE
RuntimeError: 'OBDErrorCode' object has no attribute 'formate'

### ISSUE THREAD

**Issue by lucky0604** [oceanbase/obdeploy#97]
使用`obd cluster start cluster-name`启动时报错
![image](https://user-images.githubusercontent.com/8739018/163112155-56d77ba9-8518-4633-ad9c-a51c2030cd7f.png)
查看是`.obd/plugins/oceanbase-ce/3.1.0`目录下的`start_check.py`文件中一处拼写错误
![image](https://user-images.githubusercontent.com/8739018/163112280-ca9256b6-a688-442e-aa30-0dc0604f2b1b.png)

**Comment by frf12** [comment]
Thank for feedback. This problem has been fixed in #96
